
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LPAREN MAIS MENOS NUM RPARENexp : exp MAIS exp1 \n           | exp MENOS exp1 \n           | exp1exp1 : NUM'
    
_lr_action_items = {'NUM':([0,4,5,],[3,3,3,]),'$end':([1,2,3,6,7,],[0,-3,-4,-1,-2,]),'MAIS':([1,2,3,6,7,],[4,-3,-4,-1,-2,]),'MENOS':([1,2,3,6,7,],[5,-3,-4,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,],[1,]),'exp1':([0,4,5,],[2,6,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> exp MAIS exp1','exp',3,'p_exp','expression_parser.py',5),
  ('exp -> exp MENOS exp1','exp',3,'p_exp','expression_parser.py',6),
  ('exp -> exp1','exp',1,'p_exp','expression_parser.py',7),
  ('exp1 -> NUM','exp1',1,'p_exp1','expression_parser.py',11),
]
